package com.hm.entity;
// default package
// Generated Nov 20, 2017 11:16:55 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Csvdata generated by hbm2java
 */
@Entity
@Table(name = "CSVData")
public class Csvdata implements java.io.Serializable {

	private Integer idCsvdata;
	private String name;
	private Integer age;

	public Csvdata() {
	}

	public Csvdata(String name, Integer age) {
		this.name = name;
		this.age = age;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCSVData", unique = true, nullable = false)
	public Integer getIdCsvdata() {
		return this.idCsvdata;
	}

	public void setIdCsvdata(Integer idCsvdata) {
		this.idCsvdata = idCsvdata;
	}

	@Column(name = "Name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

}
